version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: vikkimrrr7
      POSTGRES_PASSWORD: VikaVikaGo78
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data